spring.application.name=api

# Database Connection
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.xtofmklbluzqviypbnjq&password=CSUMBCST438
spring.datasource.username=postgres.xtofmklbluzqviypbnjq
spring.datasource.password=CSUMBCST438
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
